/* ==========================================================================
 * EscOut.h — ESC servo-signal output on PIN_ESC_SIG.
 *
 * Generated by arduino-pico's bundled Servo library (writeMicroseconds()),
 * which runs the pulse train on a PIO state machine: exact microsecond
 * pulses, zero CPU, and a fixed 20 ms (50 Hz) frame — the standard servo
 * rate every ESC accepts. The frame period is a compile-time constant in
 * that library, so it is not adjustable here.
 *
 * WHY NOT analogWrite (the v3.1 bug). arduino-pico's analogWriteFreq() clamps
 * anything under 100 Hz up to 100 Hz, silently. v3.1 asked for 50 Hz with
 * analogWriteRange(20000) so the duty value would read as microseconds; the
 * slice actually ran a 10 ms frame across 20000 counts, so every pulse came
 * out at HALF width — "1000 us idle" was 500 us. Some ESCs reject that as an
 * invalid signal and never arm; others read it as zero throttle.
 *
 * SAFETY.
 *  - OFF at boot: escBegin() drives the pin LOW as plain GPIO and does not
 *    attach the servo, so a board that resets mid-test does not come back
 *    spinning.
 *  - Attach is always attach(pin, 1000, 2000, 1000). The library's default
 *    attach(pin) starts at DEFAULT_NEUTRAL_PULSE_WIDTH = 1500 us — half
 *    throttle on the very first frame for a unidirectional ESC.
 *  - ARMING ALWAYS STARTS AT IDLE. escArm(true) resets the set point to
 *    ESC_PULSE_MIN_US and holds it for ESC_ARM_HOLD_MS before anything else
 *    is emitted. ESCs refuse to arm if their first frames carry throttle.
 *    Stepper presses during the hold update the set point; it is applied when
 *    the hold ends. A cycle started while disarmed arms, holds, then begins at
 *    its low end.
 *  - Disarm detaches (the library waits for the frame in progress to finish,
 *    up to 20 ms, so no runt pulse) and then drives the pin LOW as GPIO.
 *
 * THREADING. Core 0 only — escTick() is driven from the main loop and the
 * setters are called from touch handlers that already run there. Core 1 only
 * ever READS gEscOutUs, to stamp log records with what was on the pin.
 * ========================================================================*/
#pragma once
#include <Arduino.h>

#define ESC_PULSE_MIN_US   1000     /* idle / zero throttle                */
#define ESC_PULSE_MAX_US   2000
#define ESC_FRAME_US       20000    /* fixed by the Servo library (50 Hz)  */
#define ESC_ARM_HOLD_MS     2000    /* idle held after every arm           */

/* The pulse currently on the pin in us, 0 while disarmed. Core 0 writes it
 * whenever the PWM level changes; core 1 reads it into each log record. */
extern volatile uint16_t gEscOutUs;

void escBegin();          /* pin low, output disarmed. Call from setup()   */
void escTick();           /* arm hold + auto-cycle. Call every loop()      */

/* ---- manual control ---- */
void     escArm(bool on); /* true: idle + hold. false also stops any cycle */
bool     escArmed();
bool     escHolding();                /* armed, still inside the idle hold */
uint32_t escHoldRemainMs();
void     escSetPulse(uint16_t us);    /* clamped to ESC_PULSE_MIN/MAX_US   */
uint16_t escPulse();                  /* the set point                     */

/* ---- auto-cycle ----
 * Alternates between gSet.cycleLoUs and gSet.cycleHiUs, dwelling cycleLoMs
 * and cycleHiMs at each end. Starting a cycle arms the output (with the idle
 * hold if it was disarmed); stopping it leaves the output armed at the low
 * pulse, which for an ESC is idle. */
void escCycleStart();
void escCycleStop();
bool escCycling();
bool escCycleAtHigh();    /* true while dwelling at the high pulse         */
uint32_t escCycleRemainMs();   /* ms left in the current dwell, for the UI */

/* One-line state dump (armed/hold/cycle, set point, pulse on the pin). */
void escPrint(Print &out);
