#!/usr/bin/env python3
"""Generate a JCR_TouchScreen bitmap font header from any TrueType font.

    python make_fonts.py --font RussoOne-Regular.ttf --size 30 \
                         --name RUSSO22 --out RussoOne22.h

Output is a .h defining a `const JCRFont <NAME>;` you can pass to
JCR_Text::setFont(). Include it from your sketch alongside <JCR_TouchScreen.h>.

Glyph storage matches what JCR_Text expects: column-major, bit 0 = top row,
ceil(height/8) bytes per column, with per-glyph offset/width/advance tables.

Notes
-----
--mono forces a uniform advance (tabular figures). Use it for any number that
updates in place: every glyph then occupies the same cell, so the field width
never shifts and a cached redraw erases exactly what it drew.

--chars restricts the character set. Smaller sets mean smaller tables — a
digits-only font for a big readout costs a fraction of a full alphabet.

The license of the TTF you pass in governs the generated data. The library's
own JCR_Font5x7 was drawn from scratch and is MIT like the rest of the code;
anything you generate here is yours to check.

Requires Pillow:  pip install pillow
"""

import argparse
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Pillow is required:  pip install pillow")

DEFAULT_CHARS = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:-+/%()<>[]!?'#*=_&@"


def build(ttf_path, px, charset, mono=False, spacing=2, first=32, last=90):
    font = ImageFont.truetype(ttf_path, px)

    # Common vertical extent across the charset, so every glyph shares a baseline.
    tops, bottoms = [], []
    for ch in charset:
        if ch == " ":
            continue
        box = font.getbbox(ch)
        if box:
            tops.append(box[1])
            bottoms.append(box[3])
    if not tops:
        sys.exit("no renderable glyphs in the requested character set")
    top, bottom = min(tops), max(bottoms)
    height = bottom - top
    bytes_per_col = (height + 7) // 8

    data, offsets, widths, advances = [], [], [], []
    previews = {}

    for code in range(first, last + 1):
        ch = chr(code)
        if ch not in charset:
            offsets.append(0)
            widths.append(0)
            advances.append(0)
            continue
        if ch == " ":
            offsets.append(0)
            widths.append(0)
            advances.append(max(3, int(px * 0.30)))
            continue

        box = font.getbbox(ch)
        w = box[2] - box[0]
        img = Image.new("1", (box[2] + 2, bottom + 2), 0)
        ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
        px_access = img.load()

        offsets.append(len(data))
        widths.append(w)
        advances.append(w + spacing)

        cols = []
        for cx in range(w):
            col = [0] * bytes_per_col
            for ry in range(height):
                if px_access[box[0] + cx, top + ry]:
                    col[ry >> 3] |= 1 << (ry & 7)
            cols.append(col)
            data.extend(col)
        previews[ch] = (w, cols)

    if mono:
        widest = max(a for a in advances if a)
        advances = [widest if a else 0 for a in advances]

    return {
        "data": data, "offsets": offsets, "widths": widths, "advances": advances,
        "height": height, "bytes_per_col": bytes_per_col,
        "first": first, "last": last, "previews": previews,
    }


def emit(f, name, ttf_path, px, uppercase):
    n = f["last"] - f["first"] + 1
    lines = [
        "/* %s — generated by make_fonts.py from %s at %dpx." % (name, ttf_path, px),
        " * Do not hand-edit; re-run the generator instead.",
        " * The source font's license governs this data. */",
        "#pragma once",
        '#include <JCR_TouchScreen.h>',
        "",
        "inline const uint8_t %s_DATA[] = {" % name,
    ]
    d = f["data"]
    for i in range(0, len(d), 16):
        lines.append("  " + ", ".join("0x%02X" % b for b in d[i:i + 16]) + ",")
    lines.append("};")
    lines.append("inline const uint16_t %s_OFF[%d] = { %s };"
                 % (name, n, ", ".join(str(v) for v in f["offsets"])))
    lines.append("inline const uint8_t %s_W[%d] = { %s };"
                 % (name, n, ", ".join(str(v) for v in f["widths"])))
    lines.append("inline const uint8_t %s_ADV[%d] = { %s };"
                 % (name, n, ", ".join(str(v) for v in f["advances"])))
    lines.append("")
    lines.append("/* inline: safe to include from any number of .cpp files. */")
    lines.append("inline const JCRFont %s = {" % name)
    lines.append("  %s_DATA, %s_OFF, %s_W, %s_ADV," % (name, name, name, name))
    lines.append("  %d,   /* height      */" % f["height"])
    lines.append("  %d,   /* bytesPerCol */" % f["bytes_per_col"])
    lines.append("  %d, %d, /* first, last */" % (f["first"], f["last"]))
    lines.append("  0, 0, /* fixedWidth/fixedAdv unused: tables above */")
    lines.append("  %s  /* uppercaseOnly */" % ("true" if uppercase else "false"))
    lines.append("};")
    return "\n".join(lines) + "\n"


def preview(f, chars):
    for ch in chars:
        if ch not in f["previews"]:
            continue
        w, cols = f["previews"][ch]
        print("--- %r (%dx%d) ---" % (ch, w, f["height"]))
        for ry in range(f["height"]):
            print("".join("#" if (cols[cx][ry >> 3] >> (ry & 7)) & 1 else "."
                          for cx in range(w)))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--font", required=True, help="path to a .ttf")
    ap.add_argument("--size", type=int, required=True, help="pixel size to rasterize at")
    ap.add_argument("--name", required=True, help="C identifier for the generated font")
    ap.add_argument("--out", help="output .h path (default: stdout)")
    ap.add_argument("--chars", default=DEFAULT_CHARS, help="characters to include")
    ap.add_argument("--mono", action="store_true",
                    help="uniform advance (tabular figures) — use for values that update in place")
    ap.add_argument("--spacing", type=int, default=2, help="px between glyphs (default 2)")
    ap.add_argument("--mixed-case", action="store_true",
                    help="keep lowercase (default maps a-z to A-Z and covers ASCII 32..90)")
    ap.add_argument("--preview", metavar="CHARS",
                    help="print these glyphs as ASCII art to eyeball the result")
    args = ap.parse_args()

    charset = set(args.chars)
    last = 122 if args.mixed_case else 90
    if not args.mixed_case:
        charset = set(c.upper() for c in charset)

    f = build(args.font, args.size, charset, mono=args.mono,
              spacing=args.spacing, first=32, last=last)
    text = emit(f, args.name, args.font, args.size, uppercase=not args.mixed_case)

    if args.preview:
        preview(f, args.preview)

    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
        print("wrote %s: %d glyph bytes, %dpx tall" % (args.out, len(f["data"]), f["height"]),
              file=sys.stderr)
    else:
        print(text)


if __name__ == "__main__":
    main()
